baseURL = 'http://example.org/'
languageCode = 'zh-TW'
title = 'cwHsueh'
theme = 'hugo-theme-stack'

[menu]
  [[menu.main]]
    name = 'Leetcode Menu'
    url = '/leetcode/menu'
    weight = 15
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'About me'
    url = '/'
    weight = 20

[params]
  mainSections = ["post"]

  [params.widgets]
    enabled = ['search']

  [params.article]
    readingTime = false

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4