baseURL = 'http://example.org/'
languageCode = 'zh-TW'
title = 'cwh'
theme = 'hugo-theme-stack'

[menu]
  [[menu.main]]
    name = 'Leetcode Menu'
    url = '/leetcode/menu'
    weight = 15
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'About me'
    url = '/'
    weight = 20

[params]
  mainSections = ["post"]